### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by EhsanFox** [EhsanFox/MediaStreamer#1]
Possible solutions:

- Add typing file
- whole rewrite in typescript

**Comment by EhsanFox** [comment]
Issued resolved in Commit 3bf29f6ed9442202e97f55700a72ad5ee9b80832 !

**Comment by jimmywarting** [comment]
why!!!
it was so perfectly fine written with JSDoc, why introduce complicated build tools?
jsdoc are as equally good as types

**Comment by EhsanFox** [comment]
> why!!! it was so perfectly fine written with JSDoc, why introduce complicated build tools? jsdoc are as equally good as types

@jimmywarting 
Supporting TS Language was a thing I had on my bucket list for this/other packages of mine, since I have switched to Typescript myself too, it's just better, and easier for me and everyone else, although, I had plans to have jsdoc in typescript too, having no time is kind of a problem for me too, I appreciate any pull requests.

Also, what is up with build tools? they won't run any build command or anything like that on your project, they will be published as js to the npm registry, by my Github action, so no worries, no build tools and stuff needed for you, you can still use the package as fine as it was. ✨

**Comment by jimmywarting** [comment]
bit annoying when helping out and creating PR - requires build tool then...
a problem i have with most other typescript projects are that they are always bundled into one single large file and not well code splited. it's sometimes minified and so obfusicated sometimes and not the original source code. and typescript files can't be imported/supported in browsers or nodejs anyways and will always require running a compiler beforehand

https://jimmywarting.github.io/you-might-not-need-typescript/

**Comment by EhsanFox** [comment]
@jimmywarting 

There are multiple js files that are compiled from typescript, however, yes, the files might be a bit overwhelming and huge, but, supporting typescript is just better because there will be some people who will use this package in their typescript project,

we can also support typescript by creating typings and stuff, but it's just a waste of time when I can code it in ts itself,

Also, this package is not runnable in Browsers, since it uses FFmpeg installed on a computer, so, I don't see how ts is bad when it can create typing files and stuff like that, in case of some kb space of files, I would rather use TypeScript.

**Comment by jimmywarting** [comment]
i know it is specific to node/backend but i was talking about it in a more general terms. 
i wanted to fork / improve and try to help and solve bug fixes. but i just hate working in TS files.

**Comment by EhsanFox** [comment]
Also, I have checked your blog that u sent, but still, after working 2 years with doc and typescript, I rather use typescript, because I don't know how you think typescript is "Too compact to read", but it's still better than writing 10-20 commented files, which won't support typescript users either.

**Comment by jimmywarting** [comment]
> Too compact to read
```ts
function x <T extends { name?: string }>(obj: T): Omit<T, 'name'> {
```
is this clear at first glance at what it actually dose?
i don't think so...

**Comment by EhsanFox** [comment]
> i know it is specific to node/backend but i was talking about it in a more general terms. i wanted to fork / improve and try to help and solve bug fixes. but i just hate working in TS files.

@jimmywarting 
The package repo has everything required to build/compile the package, nothing needed to be installed from anywhere else (except FFmpeg), also, if you can't create a PR in order to fix any issue, you can feel free to open an issue, I would have a look into it as soon as I can.

**Comment by jimmywarting** [comment]
jsdoc comments do support typescript users as well. and you can generate d.ts file from it too
when there isn't any d.ts availble then it will parse the code

**Comment by EhsanFox** [comment]
> > Too compact to read
> 
> ```ts
> function x <T extends { name?: string }>(obj: T): Omit<T, 'name'> {
> ```
> 
> is this clear at first glance at what it actually dose? i don't think so...

you are right in some cases, such as above, but not for a small package like MediaStreamer, I don't work or write anything that complex or anything(at least not for this package), so for small things like this package, I rather go on with TypeScript.

**Comment by EhsanFox** [comment]
> jsdoc comments do support typescript users as well. and you can generate d.ts file from it too when there isn't any d.ts availble then it will parse the code

I have tried it, but at least for me, it was not at the point where I wanted to be, either way, I rather write a 5 line interface in typescript instead of writing 20 lines of comments in JSDoc.

**Comment by jimmywarting** [comment]
> so for small things like this package, I rather go on with TypeScript.

🤔 think some might reason the other way around and say the opposite
but then it's usually micro libraries that is just like one file and 100 lines of code... then ts isn't worth including in a such tiny micro module.

ppl often say ts is good for larger work. and some ppl avoid it when writing personal stuff with rapid prototyping. 

---

anyway. i did not end up using your module anyway... started to work on it and tried to implement some new feature stuff but this didn't do much for me. 
so I forked https://www.npmjs.com/package/live-stream-radio instead and started working on that instead which is vanilla js which i prefer more over TS

as that was my main purpose to have a 24/7 radio channel

**Comment by EhsanFox** [comment]
well, I can't say anything about this, anyone has their own ideas I guess, good luck with the project.❤

**Comment by jimmywarting** [comment]
same, Dito, Good luck with MediaStreamer
